# Linear algebra with NumPy

This notebook will cover linear algebra operations using NumPy. NumPy provides a comprehensive set of linear algebra functions that enable efficient manipulation and computation of matrices and vectors.

In [1]:
import numpy as np

### Creating vectors and matrices

NumPy arrays are used to represent vectors and matrices. We can create them using the `np.array` function.

In [2]:
# Creating a vector
vector = np.array([1, 2, 3])
print("Vector:", vector)

# Creating a matrix
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]


## Vector operations

- **Dot product**: Computes a scalar value from two arrays. For 1D arrays, it is the inner product. For 2D arrays, it is matrix multiplication.
- **Inner product**: Computes a scalar value or a reduced result from higher-dimensional arrays. For 1-D arrays, it is equivalent to the dot product. For higher dimensions, it reduces the last axis of the first array with the second array.
- **Outer product**: Produces a matrix from two vectors.
- **Vdot product**: Similar to the dot product, but with conjugation for complex numbers.

In [3]:
# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)

# Inner product
inner_product = np.inner(a, b)
print("Inner product:", inner_product)

# Outer product
outer_product = np.outer(a, b)
print("Outer product:\n", outer_product)

# Vdot product
a = np.array([1 + 2j, 3 + 4j])
b = np.array([5 + 6j, 7 + 8j])
vdot_product = np.vdot(a, b)
print("Vdot product:", vdot_product)

Dot product: 32
Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Vdot product: (70-8j)


## Vector properties

### Norms

Norms are used to measure the size or length of vectors and matrices. The most common is the L2 norm, or Euclidean norm. The L2 norm is calculated as the square root of the sum of the squares of the vector's elements.

In [4]:
# Calculating the norm
vector = np.array([3, 4])
norm = np.linalg.norm(vector)
print("L2 Norm:", norm)

L2 Norm: 5.0


## Matrix operations

### Matrix multiplication
We can perform matrix multiplication using `np.dot`, `@` operator, or `np.matmul`. Each element in the resulting matrix is the dot product of the corresponding row from the first matrix and the column from the second matrix.

In [5]:
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Using np.dot
product = np.dot(matrix1, matrix2)
print("Matrix product using np.dot:\n", product)

# Using @ operator
product = matrix1 @ matrix2
print("Matrix product using @ operator:\n", product)

# Using np.matmul
product_matmul = np.matmul(matrix1, matrix2)
print("Matrix product using np.matmul:\n", product_matmul)

Matrix product using np.dot:
 [[19 22]
 [43 50]]
Matrix product using @ operator:
 [[19 22]
 [43 50]]
Matrix product using np.matmul:
 [[19 22]
 [43 50]]


### Matrix power
Matrix power computes the matrix raised to an integer power.

In [6]:
# Matrix power
matrix = np.array([[1, 2], [3, 4]])
powered_matrix = np.linalg.matrix_power(matrix, 2)
print("Matrix to the power of 2:\n", powered_matrix)

Matrix to the power of 2:
 [[ 7 10]
 [15 22]]


### Transpose of a matrix

In [7]:
# 2D array transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix:\n", matrix)
transposed_matrix = matrix.T
print("Transposed matrix:\n", transposed_matrix)

# Higher-dimensional array transpose
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nOriginal 3D array:\n", array_3d)
transposed_3d = array_3d.transpose(1, 0, 2)
print("Transposed 3D array:\n", transposed_3d)

Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]

Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Transposed 3D array:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## Matrix properties

### Determinant of a matrix

The determinant is a scalar value that can be computed from the elements of a square matrix. It provides important properties about the matrix, such as invertibility. A non-zero determinant indicates the matrix is invertible.

We also can compute the sign and natural logarithm of the determinant of a matrix with `np.linalg.slogdet`.

In [8]:
# Calculating the determinant
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

sign, logdet = np.linalg.slogdet(matrix)
print("Sign:", sign)
print("Log-determinant:", logdet)

Determinant: -2.0000000000000004
Sign: -1.0
Log-determinant: 0.6931471805599455


### Inverse of a matrix

The inverse of a matrix is another matrix such that when multiplied together, they yield the identity matrix. Not all matrices have inverses. Exists only for square matrices with a non-zero determinant. It "undoes" the transformation represented by the original matrix.

In [9]:
# Calculating the inverse
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print("Inverse of the matrix:\n", inverse)

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Rank
Computes the rank of a matrix, i.e., the number of linearly independent rows or columns.

In [10]:
# Matrix rank
matrix = np.array([[1, 2], [3, 4]])
rank = np.linalg.matrix_rank(matrix)
print("Matrix rank:", rank)

Matrix rank: 2


### Trace
Computes the sum of the diagonal elements of a matrix.

In [11]:
# Trace of a matrix
matrix = np.array([[1, 2], [3, 4]])
trace = np.trace(matrix)
print("Trace:", trace)

Trace: 5


### Diagonal elements of a matrix
Extracts the diagonal elements of a matrix or a 2D slice of a higher-dimensional array.

In [12]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extracting the main diagonal
main_diagonal = np.diagonal(matrix)
print("Main diagonal:", main_diagonal)

# Extracting the diagonal above the main diagonal
upper_diagonal = np.diagonal(matrix, offset=1)
print("Upper diagonal:", upper_diagonal)

Main diagonal: [1 5 9]
Upper diagonal: [2 6]


**Syntax**: 
```python
diagonal_elements = np.diagonal(array, offset=0, axis1=0, axis2=1)
```

- `offset`: The diagonal offset; `0` is the main diagonal, positive values are above, and negative values are below the main diagonal.
- `axis1` and `axis2`: The two axes to consider; by default, it looks at the first two dimensions.

### Eigenvalues and eigenvectors

Provide information about the behavior of linear transformations. An eigenvector is a direction that remains unchanged, while an eigenvalue is a factor by which it is scaled.

In [13]:
# Calculating eigenvalues and eigenvectors
matrix = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## Matrix decompositions

- ***Singular value decomposition (SVD)*** - SVD is a factorization of a matrix into three matrices, often used in dimensionality reduction and data compression. It decomposes a matrix into three other matrices (`U`, `S`, `Vt`).

- ***Cholesky decomposition*** - The Cholesky decomposition factors a positive-definite matrix into a lower triangular matrix and its transpose. It used for solving linear systems and in various optimization problems.

In [14]:
# Singular Value Decomposition
matrix = np.array([[1, 2, 3], [4, 5, 6]])
U, S, Vt = np.linalg.svd(matrix)
print("SVD decomposition:")
print("U matrix:\n", U)
print("Singular values:", S)
print("Vt matrix:\n", Vt)

# Cholesky Decomposition
matrix = np.array([[4, 2], [2, 2]])
L = np.linalg.cholesky(matrix)
print("\nCholesky decomposition:")
print("Cholesky factor L:\n", L)

SVD decomposition:
U matrix:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Singular values: [9.508032   0.77286964]
Vt matrix:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]

Cholesky decomposition:
Cholesky factor L:
 [[2. 0.]
 [1. 1.]]


## Tensor operations

### Tensor dot product

The tensor dot product generalizes the concept of dot products to arrays with more than two dimensions. It computes the sum of the product of elements across specified axes of the tensors.

In [15]:
# Tensor dot product
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Perform tensor dot product over specified axes
result = np.tensordot(a, b, axes=([1], [0]))
print("Tensor dot product:\n", result)

Tensor dot product:
 [[19 22]
 [43 50]]


- **Syntax**: `result = np.tensordot(a, b, axes=([axis1], [axis2]))`

  - `a` and `b` are the input arrays (tensors).
  - `axes` specifies the axes over which the sum of products is computed. It is a tuple of two sequences, each containing the axes for each input array.

## Solving linear systems

In linear algebra, solving a system of linear equations involves finding the values of variables that satisfy all the given equations simultaneously. For instance, given a system of equations in matrix form: 
$$ Ax = b $$ 
Where:

- A is a matrix of coefficients.
- x is the vector of unknowns we want to find.
- b is the vector of constants on the right-hand side of the equations.

The goal is to find the vector `x`. We can solve systems of linear equations using NumPy's `np.linalg.solve` function.

To ensure that the solution is correct, we can substitute the solution back into the original equations and verify if `Ax` equals `b`. This can be done using `np.allclose` to handle floating-point precision issues.

In [16]:
# Solving a system of equations
A = np.array([[1, 1], [1, -1]])
b = np.array([5, 1])

solution = np.linalg.solve(A, b)
print("Solution:", solution)

# Verify the solution
is_correct = np.allclose(np.dot(A, solution), b)
print("Is the solution correct?", is_correct)

Solution: [3. 2.]
Is the solution correct? True


The matrix `A` contains coefficients, while vector `b` contains constants.

- Syntax: `np.linalg.solve(A, b)`
- Parameters:
    - `A`: A square matrix representing the coefficients of the linear equations. The shape of `A` should be `(n, n)`.
    - `b`: A vector or matrix representing the constants on the right side of the equations. The shape of `b` should be `(n,)` for a vector or `(n, m)` for a matrix with multiple right-hand sides.
    
Here, `np.allclose` checks if the computed values are close enough to the actual values, accounting for numerical precision. If `is_correct` is `True`, it means the solution is accurate.

While `np.linalg.solve` is used to find exact solutions to a system of linear equations (when the system is square and has a unique solution), `np.linalg.lstsq` is used to find the least squares solution to a system that may be overdetermined or underdetermined.

## Linear regression - Least squares method
When dealing with linear systems, sometimes the number of equations does not exactly match the number of unknowns. In such cases, we might not have a perfect solution that satisfies all equations. Instead, we can find the best possible solution that minimizes the discrepancy between the left and right sides of the equations. This is where the least squares method comes in.

In matrix form, the problem can be expressed as:
$$ A \cdot x \approx b $$

where:
- A is an $(m \times n)$ matrix (with $(m \geq n)$ for an overdetermined system, or $(m \leq n)$ for an underdetermined system).
- x is an $(n \times 1)$ vector of unknowns.
- b is an $(m \times 1)$ vector of constants.

The goal is to find \(x\) that minimizes the sum of squared residuals:
$$\text{minimize} \|A \cdot x - b\|^2$$

In linear regression, we typically have a model of the form:

$$ y = A \cdot \beta + \epsilon $$

Where:
- y is the vector of observed values.
- A is the matrix of predictor variables (including a column for the intercept if necessary).
- $\beta$ is the vector of coefficients to be estimated.
- $\epsilon$ is the error term.

In [17]:
# Coefficient matrix
A = np.array([1, 2, 3, 4, 5])
# Prepare matrix A with an intercept term
A = np.vstack([A, np.ones(len(A))]).T

# Constants vector
b = np.array([2.2, 2.8, 3.6, 4.5, 5.1])

# Solve for the least squares solution
coefficients_linear, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

# Compute the predicted values
best_fit_linear = A @ coefficients_linear

equation = f"y = {coefficients_linear[0]:.4f}x + {coefficients_linear[1]:.4f}"
print("Least squares solution:", coefficients_linear)
print("Residuals:", residuals)
print("Rank of matrix:", rank)
print("Singular values:", s)
print("Equation of the best fit line:", equation)

Least squares solution: [0.75 1.39]
Residuals: [0.027]
Rank of matrix: 2
Singular values: [7.69121313 0.91936964]
Equation of the best fit line: y = 0.7500x + 1.3900


**Explanation:**

- **Syntax**: `coefficients, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)`

- **Parameters**:
  - `A`: The input matrix representing the system of equations. In the context of linear regression, this is typically the design matrix containing the features (and possibly a column of ones for the intercept).
  - `b`: The dependent variable vector (e.g., the `y` values you are trying to predict).
  - `rcond`: A cutoff for small singular values. It helps determine the effective rank of `A`. Values smaller than this are considered zero. If set to `None`, a default value is used.

- **Returns**:
  - `coefficients`: The solution array containing the coefficients that minimize the squared differences between the observed values (`b`) and the predicted values (`A @ coefficients`).
  - `residuals`: The sum of the squared residuals of the solution. This is only returned if `A` is of full rank and `b` has more rows than columns.
  - `rank`: The effective rank of the matrix `A`.
  - `singular_values`: The singular values of `A`, which provide information about the stability and condition of the matrix.