# Introduction to NumPy

NumPy, short for Numerical Python, is a library for numerical computations in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently.

##### Why use NumPy?
- Performance: NumPy is highly optimized and implemented in C, making it much faster than using Python lists for numerical operations.
- Memory efficiency: NumPy arrays are more compact and efficient in terms of memory usage compared to Python lists.
- User-friendly: Provides convenient syntax and functions for mathematical operations on arrays and matrices.
- Integration: Compatible with many other scientific computing and data analysis libraries like SciPy, Matplotlib, and Pandas.

In [1]:
# Importing NumPy
import numpy as np

It is common to import NumPy with the alias `np`

### Creating arrays
NumPy's main feature is the `ndarray` (N-dimensional array) object. We can create arrays using several methods.

#### 1. From a Python list

In [2]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", array_1d)

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", array_2d)

# Creating a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]], 
                     [[13, 14, 15], [16, 17, 18]]])
print("3D Array:\n", array_3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In the example above:
- The 1D array is a simple list of numbers.
- The 2D array is a list of lists, where each inner list represents a row.
- The 3D array is a list of lists of lists, where each innermost list represents a slice along the third dimension.

#### 2. Using built-in functions

NumPy provides functions to create arrays of zeros, ones, or empty arrays.

In [3]:
# Array of zeros
zeros = np.zeros((2, 3))
print("Array of zeros:\n", zeros)

# Array of ones
ones = np.ones((2, 3))
print("Array of ones:\n", ones)

# Identity matrix
identity = np.eye(3)
print("Identity matrix:\n", identity)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 3. Using random functions

NumPy provides various functions to generate arrays with random numbers. These functions are useful for simulations, testing algorithms, and more.

In [4]:
# Creates a 5x3 array with random numbers between 0 and 1
random_array = np.random.rand(5, 3)
print("Random array (uniform distribution):\n", random_array)

# Creates an array of 5 random integers between 0 and 10
random_integers = np.random.randint(10, size=5)
print("1D Array with random integers:\n", random_integers)
# Generates a 2D array with shape (3, 4) filled with random integers between 0 and 10
random_integers_2d = np.random.randint(10, size=(3, 4))
print("2D Array with random integers:\n", random_integers_2d)


# Set the seed for reproducibility
np.random.seed(42)
# Generate random numbers after setting the seed
seeded_random_array = np.random.rand(3, 3)
print("Seeded random array:\n", seeded_random_array)

Random array (uniform distribution):
 [[0.96223799 0.80311488 0.42143921]
 [0.82331669 0.14635052 0.52896655]
 [0.27448289 0.18760872 0.90412416]
 [0.83979563 0.08753925 0.484084  ]
 [0.79582075 0.37569574 0.91328805]]
1D Array with random integers:
 [2 3 7 8 3]
2D Array with random integers:
 [[2 9 4 8]
 [9 4 7 0]
 [7 2 1 9]]
Seeded random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


1. `np.random.rand` - Generates an array of random numbers from a uniform distribution over `[0, 1)`. The shape of the array is determined by the dimensions `d1, d2, ..., dn` we specify.
    - **Syntax**: `np.random.rand(d1, d2, ..., dn)`

2. `np.random.randint` - Generates an array of random integers from a discrete uniform distribution. We specify the range of values (`low` to `high`) and the shape of the array (`size`).
    - **Syntax**: `np.random.randint(low, high=None, size=None, dtype=int)`
      - `low`: Lowest integer to be included in the array.
      - `high`: Upper bound (exclusive) for the random integers. If `None`, it defaults to `low`.
      - `size`: Shape of the output array. Can be a single integer or a tuple.
      - `dtype`: Desired data type of the result (default is `int`).

3. `np.random.seed` - Initializes the random number generator to ensure reproducibility. A seed is an initial value used by a pseudo-random number generator (PRNG) to produce a sequence of numbers. These numbers are not truly random but are generated algorithmically to mimic randomness. The seed value acts as a starting point for the sequence. Given the same seed, a PRNG will always produce the same sequence of numbers, making it deterministic.
    - **Syntax**: `np.random.seed(seed)`
    
    Setting the seed allows us to produce the same random numbers each time we run our code. If we use the same seed, we'll get the same sequence of random numbers every time, which is useful for debugging and testing. Setting the seed with `np.random.seed` affects all subsequent random number generation until the seed is changed again. It sets the seed globally for all NumPy random functions. If you need different sequences of random numbers in different parts of your code but still want reproducibility, you can reset the seed at various points using `np.random.seed`.

#### 4. Creating arrays with a range of values

NumPy provides functions that allow us to create arrays with a sequence of numbers easily. Two commonly used functions for this purpose are `arange` and `linspace`.

In [5]:
# Using arange
range_array = np.arange(10)
print("Range Array:", range_array)

# Using linspace
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)

Range Array: [0 1 2 3 4 5 6 7 8 9]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


1. Using `arange` - The `arange` function generates an array with evenly spaced values within a specified range. The general syntax for `arange` is:
    ```python
    np.arange(start, stop, step)
    ```

    - `start`: The starting value of the sequence (inclusive). If not specified, it defaults to 0.
    - `stop`: The end value of the sequence (exclusive). The sequence stops before this value.
    - `step`: The spacing between values. (optional, default is 1)

2. Using `linspace` - The `linspace` function generates an array with a specified number of evenly spaced values over a given range. The general syntax for `linspace` is:
    ```python
    np.linspace(start, stop, num)
    ```

    - `start`: The starting value of the sequence (inclusive).
    - `stop`: The end value of the sequence (inclusive).
    - `num`: The number of values to generate. The spacing between values will be automatically calculated to evenly distribute the numbers between `start` and `stop`.

Unlike `arange`, which defines the spacing between values, `linspace` defines the total number of values and automatically calculates the spacing. This is particularly useful when we want to create an array with a specific number of points between two values.


## Array operations

NumPy supports a variety of operations on arrays. These operations can be broadly categorized into element-wise operations, universal functions, and statistical functions.

### Element-wise operations
Element-wise operations are performed on corresponding elements of arrays.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


### Universal functions

Universal functions (ufuncs) perform mathematical operations on each element of an array independently. They are highly optimized for performance and can handle arrays of any shape.
- **Syntax**: `result = np.<function>(array)`
  - `<function>` can be `sqrt`, `exp`, `sin`, etc.

#### Mathematical functions

##### Exponential and logarithmic functions

These functions include exponentials and logarithms, which are widely used in scientific calculations.

In [7]:
# Exponential and logarithmic functions
a = np.array([1, 2, 3])

print("Exponential:", np.exp(a))
print("Exponential minus 1:", np.expm1(a))
print("Exponential base 2:", np.exp2(a))
print("Natural logarithm:", np.log(a)) # natural log
print("Base 10 logarithm:", np.log10(a)) # base 10 log (common logarithm)
print("Base 2 logarithm:", np.log2(a)) # base 2 log (binary logarithm)
print("Logarithm of 1 plus value:", np.log1p(a))

Exponential: [ 2.71828183  7.3890561  20.08553692]
Exponential minus 1: [ 1.71828183  6.3890561  19.08553692]
Exponential base 2: [2. 4. 8.]
Natural logarithm: [0.         0.69314718 1.09861229]
Base 10 logarithm: [0.         0.30103    0.47712125]
Base 2 logarithm: [0.        1.        1.5849625]
Logarithm of 1 plus value: [0.69314718 1.09861229 1.38629436]


##### Arithmetic operations
NumPy supports basic arithmetic operations that can be applied element-wise on arrays.

In [8]:
# Arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))
print("Multiplication:", np.multiply(a, b))
print("Division:", np.divide(a, b))
print("Remainder:", np.remainder(b, a))
print("Power:", np.power(a, 2))
print("Positive:", np.positive(a))
print("Negative:", np.negative(a))
print("Difference:", np.diff(a))
print("Gradient:", np.gradient(a)) # Computes the rate of change of the values in the array

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Remainder: [0 1 0]
Power: [1 4 9]
Positive: [1 2 3]
Negative: [-1 -2 -3]
Difference: [1 1]
Gradient: [1. 1. 1.]


##### Aggregation functions
Aggregation functions compute a single result from an array or along an axis.

In [9]:
# Aggregation functions
data = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(data))
print("Product:", np.prod(data))
print("Cumulative sum:", np.cumsum(data))
print("Cumulative product:", np.cumprod(data))

Sum: 15
Product: 120
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]


##### Rounding functions
Rounding functions are used to round numbers to the nearest integer or to a specified number of decimal places.

In [10]:
# Rounding functions
array = np.array([1.5, 2.3, -1.7, -2.5])

print("Rounded:", np.round(array))
print("Floored:", np.floor(array))
print("Ceiled:", np.ceil(array))
print("Truncated:", np.trunc(array))

Rounded: [ 2.  2. -2. -2.]
Floored: [ 1.  2. -2. -3.]
Ceiled: [ 2.  3. -1. -2.]
Truncated: [ 1.  2. -1. -2.]


##### Trigonometric functions

NumPy provides trigonometric functions that are useful for performing operations involving angles. These functions expect angles in radians.

In [11]:
# Trigonometric functions
angles_rad = np.array([0, np.pi / 6, np.pi / 4, np.pi / 3, np.pi / 2])  # Array of angles in radians
angles_deg = np.array([0, 90, 180])

print("Sine values:", np.sin(angles_rad))
print("Cosine values:", np.cos(angles_rad))
print("Tangent values:", np.tan(angles_rad))
print("\nArcsine values:", np.arcsin([0, 0.5, 1])) # Returns angles whose sine is given
print("Arccosine values:", np.arccos([1, 0.5, 0])) # Returns angles whose cosine is given
print("Arctangent values:", np.arctan([0, 1, np.inf])) # Returns angles whose tangent is given
print("\nDegrees from radians:", np.rad2deg(angles_rad)) # Convert angles from radians to degrees
print("Radians from degrees:", np.deg2rad(angles_deg)) # Convert angles from degrees to radians

Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

Arcsine values: [0.         0.52359878 1.57079633]
Arccosine values: [0.         1.04719755 1.57079633]
Arctangent values: [0.         0.78539816 1.57079633]

Degrees from radians: [ 0. 30. 45. 60. 90.]
Radians from degrees: [0.         1.57079633 3.14159265]


##### Hyperbolic functions

Hyperbolic functions are analogs of trigonometric functions for hyperbolic angles.

In [12]:
# Hyperbolic functions
values = np.array([-1.0, 0.0, 1.0, 2.0]) 

print("Hyperbolic sine values:", np.sinh(values))
print("Hyperbolic cosine values:", np.cosh(values))
print("Hyperbolic tangent values:", np.tanh(values))
print("\nInverse hyperbolic sine values:", np.arcsinh(values))
print("Inverse hyperbolic cosine values:", np.arccosh([1.0, 1.5, 2.0]))  # Note: input values must be >= 1 for arccosh
print("Inverse hyperbolic tangent values:", np.arctanh([0.0, 0.5, 0.9]))  # Note: input values must be between -1 and 1 for arctanh

Hyperbolic sine values: [-1.17520119  0.          1.17520119  3.62686041]
Hyperbolic cosine values: [1.54308063 1.         1.54308063 3.76219569]
Hyperbolic tangent values: [-0.76159416  0.          0.76159416  0.96402758]

Inverse hyperbolic sine values: [-0.88137359  0.          0.88137359  1.44363548]
Inverse hyperbolic cosine values: [0.         0.96242365 1.3169579 ]
Inverse hyperbolic tangent values: [0.         0.54930614 1.47221949]


##### Miscellaneous functions
Some other useful mathematical functions provided by NumPy.

In [13]:
# Miscellaneous functions
array = np.array([-1, -2, 3, 4])

print("Absolute value:", np.abs(array))
print("Square root:", np.sqrt(np.abs(array)))
print("Square:", np.square(array))
print("Sign:", np.sign(array))

Absolute value: [1 2 3 4]
Square root: [1.         1.41421356 1.73205081 2.        ]
Square: [ 1  4  9 16]
Sign: [-1 -1  1  1]


##### Linear interpolation

The `np.interp` function performs linear interpolation on one-dimensional data.

In [14]:
# Known data points
xp = np.array([0, 1, 2, 3, 4])
fp = np.array([0, 1, 4, 9, 16])

# Points where we want to interpolate
x = np.array([-1, 0.5, 2.5, 5])

# Linear interpolation
interp_values = np.interp(x, xp, fp)
print("Interpolated Values:", interp_values)

# Using left and right parameters
interp_left_right = np.interp(x, xp, fp, left=-1, right=20)
print("Interpolated Values with Left and Right:", interp_left_right)

Interpolated Values: [ 0.   0.5  6.5 16. ]
Interpolated Values with Left and Right: [-1.   0.5  6.5 20. ]


***Syntax:***
```python
np.interp(x, xp, fp, left=None, right=None, period=None)
```

- **`x`**: Array of x-coordinates where interpolation is to be performed.
- **`xp`**: Array of x-coordinates of known data points (must be monotonically increasing).
- **`fp`**: Array of y-coordinates of known data points corresponding to `xp`.
- **`left`** (optional): Value to return for `x < xp[0]`. If not specified, `np.interp` uses `fp[0]`.
- **`right`** (optional): Value to return for `x > xp[-1]`. If not specified, `np.interp` uses `fp[-1]`.
- **`period`** (optional): Period for periodic boundary conditions (not commonly used in simple interpolation).

***Explanation***

1. Basic linear interpolation:
   - `np.interp(x, xp, fp)` computes the interpolated values of `x` based on the known data points `xp` and `fp`.
   - For example, if `x = 0.5`, it interpolates between `xp[0] = 0` and `xp[1] = 1` to find the corresponding `fp` value, which is between `fp[0] = 0` and `fp[1] = 1`.
   - If a value in `x` is outside the bounds of `xp`, `np.interp` handles it by using the closest boundary value from `fp`:
        - Below minimum `xp`: If a point in `x` is less than the smallest value in `xp`, `np.interp` returns the first value in `fp`.
        - Above maximum `xp`: If a point in `x` is greater than the largest value in `xp`, `np.interp` returns the last value in `fp`.

2. Handling out-of-bounds values:
   - The `left` and `right` parameters control how values outside the range of `xp` are handled.
   - `left` specifies the value to return for `x < xp[0]`. In the example, `x = -1` is less than `xp[0] = 0`, so the interpolation returns `-1` instead of extrapolating.
   - `right` specifies the value to return for `x > xp[-1]`. Here, `x = 5` is greater than `xp[-1] = 4`, so the interpolation returns `20` instead of extrapolating.

#### Statistical functions

NumPy provides various functions to perform statistical operations on arrays.

In [15]:
array = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])

print("Mean:", np.mean(array))
print("Weighted average:", np.average(array, weights=weights))
print("Median:", np.median(array))
print("Minimum:", np.min(array))
print("25th percentile:", np.percentile(array, 25))
print("Quantiles (25%, 50%, 75%):", np.quantile(array, [0.25, 0.5, 0.75]))
print("Maximum:", np.max(array))
print("Index of minimum:", np.argmin(array))
print("Index of maximum:", np.argmax(array))
print("Range:", np.ptp(array))
print("Count non-zero:", np.count_nonzero(array))
print("Standard deviation:", np.std(array))
print("Variance:", np.var(array))

Mean: 3.0
Weighted average: 3.2
Median: 3.0
Minimum: 1
25th percentile: 2.0
Quantiles (25%, 50%, 75%): [2. 3. 4.]
Maximum: 5
Index of minimum: 0
Index of maximum: 4
Range: 4
Count non-zero: 5
Standard deviation: 1.4142135623730951
Variance: 2.0


Statistical functions in NumPy operate on the entire array or along a specified axis.
- **Syntax**: `result = np.<stat_function>(array, axis=None)`
  - `<stat_function>` can be `mean`, `median`, `std`, `sum`, etc.
  - If no `axis` is specified, it returns the computed value of the flattened array.
  
##### Statistical functions for two arrays
The correlation coefficient and covariance matrix functions in NumPy are used to analyze the relationship between two arrays.

In [16]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Correlation coefficient:\n", np.corrcoef(array1, array2))
print("Covariance matrix:\n", np.cov(array1, array2))

Correlation coefficient:
 [[1. 1.]
 [1. 1.]]
Covariance matrix:
 [[1. 1.]
 [1. 1.]]


Statistical functions that operate on two arrays help determine the relationship between them.

- **Syntax**: `result = np.<function>(array1, array2)`
  - `<function>` can be `corrcoef`, `cov`, etc.
  - Both `array1` and `array2` must have the same length along the specified axis.

##### Histograms

Histograms are useful for visualizing the distribution of data values in an array.

In [17]:
# Sample data
data = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5])

# Calculate histogram
hist, bin_edges = np.histogram(data, bins=5, range=(1, 5))

print("Histogram counts:", hist)
print("Bin edges:", bin_edges)

# Digitize data
indices = np.digitize(data, bin_edges)
print("Bin indices:", indices)

# Counting occurrences
counts = np.bincount(data)
print("Bin counts:", counts)

Histogram counts: [1 2 1 3 4]
Bin edges: [1.  1.8 2.6 3.4 4.2 5. ]
Bin indices: [1 2 2 3 4 4 4 6 6 6 6]
Bin counts: [0 1 2 1 3 4]


- **`np.histogram`** calculates the frequency of data values in specified bins. The `hist` array represents the counts for each bin, and `bin_edges` defines the intervals. It's syntax:
    ```python
    np.histogram(data, bins=10, range=None, density=False)
    ```
    - `data`: Input array containing the data.
    - `bins`: Number of equal-width bins or specific bin edges.
    - `range`: The lower and upper range of the bins.
    - `density`: If `True`, the result is the probability density function (PDF). It returns the frequency count of each integer value in the array. Useful for non-negative integer arrays to see how often each number occurs.

- **`np.digitize`** finds the indices of the bins to which each value in an input array belongs. It categorizes the data based on the provided bin edges. We can use it when we need to segment continuous data into discrete categories.
    - It returns an array where each element is the index of the bin to which the corresponding element in `data` belongs. For example, `1` belongs to the first bin, so its index is `1`.
    - If a data point is less than the first bin edge or greater than the last, `np.digitize` assigns indices such that they fall outside the normal range.

- **`np.bincount`**: Counts the number of occurrences of each value in an array of non-negative integers.

### Array attributes

NumPy arrays have several attributes that provide useful information about their structure and data.

In [18]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)
print("Shape:", array.shape)
print("Number of dimensions:", array.ndim)
print("Data type of elements:", array.dtype)
print("Type of array object:", type(array))
print("Size:", array.size)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Data type of elements: int32
Type of array object: <class 'numpy.ndarray'>
Size: 6


1. `shape` - Returns a tuple representing the dimensions of the array. Each value in the tuple corresponds to the size of the array along that dimension. For a 2D array, it tells you the number of rows and columns. For a 3D array, it tells you the number of layers, rows, and columns.
    - **Syntax**: `array.shape`

2. `ndim` - Returns the number of dimensions (axes) of the array. It tells us how many levels of indexing we need to access an element in the array. For example, a 2D array has rows and columns (2 dimensions), while a 3D array has layers, rows, and columns (3 dimensions).
    - **Syntax**: `array.ndim`

3. `dtype` - Returns the data type of the elements in the array. This could be integers, floats, or other types. It ensures that we understand what type of data operations are safe to perform on the array.
    - **Syntax**: `array.dtype`

4. `type(array)` - Returns the type of the array object itself. This is usually `numpy.ndarray`.
    - **Syntax**: `type(array)`
    
5. `size` - Returns the total number of elements in the array. It gives us the count of all items in the array, irrespective of its shape. It’s simply the product of all dimensions.
    - **Syntax**: `array.size`


### Indexing and slicing

NumPy arrays can be indexed and sliced similarly to Python lists.

In [19]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Indexing
print("First element:", array[0])
print("Last element:", array[-1])

# Indexing in 2D arrays
print("Element at (0, 0):", array_2d[0, 0])
print("Element at (1, 2):", array_2d[1, 2])

# Boolean indexing
bool_index = array > 25
print("Elements greater than 25:", array[bool_index])

# Fancy indexing
indices = [0, 2, 4]
print("Selected elements:", array[indices])

# Modifying elements
array[1] = 10
print("Modified array:", array)

# Conditional assignment
array[array > 55] = 100
print("Modified array with condition:", array)

# Slicing
print("Elements from index 1 to 3:", array[1:4])
print("Every second element:", array[::2])

# Slicing in 2D arrays
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Second row:", array_2d[1, :])
print("Last column:", array_2d[:, -1])
print("Middle column:", array_2d[:, 1:-1])

First element: 10
Last element: 80
Element at (0, 0): 1
Element at (1, 2): 6
Elements greater than 25: [30 40 50 60 70 80]
Selected elements: [10 30 50]
Modified array: [10 10 30 40 50 60 70 80]
Modified array with condition: [ 10  10  30  40  50 100 100 100]
Elements from index 1 to 3: [10 30 40]
Every second element: [ 10  30  50 100]
Second row: [4 5 6]
Last column: [3 6 9]
Middle column: [[2]
 [5]
 [8]]


1. Indexing - Indexing in NumPy arrays allows us to access specific elements based on their position in the array.
- **Syntax**: `array[index]`
  - Accesses the element at the specified `index`.
  - Indexing starts at 0, and negative indices access elements from the end of the array.

    1.1 Accessing elements in 2D arrays - We can access specific elements in a 2D array using two indices.
    - **Syntax**: `array_2d[row_index, col_index]`
    
    1.2 Boolean indexing - Select elements based on a condition.
    1.3 Fancy indexing - Select elements using an array of indices.
    1.4. Modifying elements - We can modify elements in a NumPy array by assigning new values using indexing.

2. Slicing - Slicing allows us to access a range of elements within an array.
- **Syntax**: `array[start:stop:step]`
  - `start`: The starting index (inclusive).
  - `stop`: The ending index (exclusive).
  - `step`: The interval between elements (default is 1).
  
    2.1. Slicing in 2D arrays - For 2D arrays, we can slice rows and columns using a similar syntax, but with a comma to separate row and column indices.
    - **Syntax**: `array_2d[row_start:row_stop, col_start:col_stop]`
    
### Broadcasting
Broadcasting describes how NumPy handles arithmetic operations between arrays of different shapes. When performing operations like addition, subtraction, multiplication, or division, NumPy automatically expands the smaller array to match the shape of the larger array so that the operation can be performed element-wise. The smaller array is "broadcast" across the larger array so that they have compatible shapes.

**Broadcasting rules** - The following rules determine how broadcasting works:

   - **Rule 1**: If the arrays differ in their number of dimensions, the shape of the smaller-dimensional array is padded with ones on its left side until both shapes have the same length.

   - **Rule 2**: Arrays with a dimension of size 1 can be stretched to match the other array's dimension. If the corresponding dimension sizes are equal, or one of them is 1, they are compatible.

   - **Rule 3**: If there are still incompatible dimensions after applying rules 1 and 2, broadcasting cannot occur, and an error is raised.

In [20]:
# Broadcasting addition
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print("Broadcasted addition:\n", a + b)

# Broadcasting scalar
c = np.array([1, 2, 3, 4])
result = c + 10
print("Broadcasted addition with scalar:\n", result)

# Broadcasting subtraction
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])
result = x - y
print("Broadcasted subtraction:\n", result)

# Attempting incompatible broadcasting
try:
    z = np.array([1, 2, 3])
    w = np.array([[1, 2], [3, 4], [5, 6]])
    result = z + w
except ValueError as e:
    print("Error:", e)

Broadcasted addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]
Broadcasted addition with scalar:
 [11 12 13 14]
Broadcasted subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]
Error: operands could not be broadcast together with shapes (3,) (3,2) 


**Explanation**:

1. Broadcasting addition -
   - **Shape of `a`**: `(3,)` (1D array)
   - **Shape of `b`**: `(3, 1)` (2D array)

   Here, `a` is broadcast to become a `(3, 3)` array by replicating its values along a new axis:
   ```
   [[1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]]
   ```

   The addition is performed element-wise, resulting in:
   ```
   [[2, 3, 4],
    [3, 4, 5],
    [4, 5, 6]]
   ```

2. Broadcasting with scalars -
   - **Shape of `c`**: `(4,)`
   - **Shape of scalar `10`**: `()` (a scalar, treated as `(1,)`)

   The scalar `10` is broadcast to become a `(4,)` array `[10, 10, 10, 10]`, and the addition is performed element-wise:
   ```
   [11, 12, 13, 14]
   ```

3. Multi-dimensional broadcasting -
   - **Shape of `x`**: `(2, 3)`
   - **Shape of `y`**: `(3,)`

   The array `y` is broadcast to match the shape `(2, 3)` by replicating across the new axis:
   ```
   [[10, 20, 30],
    [10, 20, 30]]
   ```

   Subtraction is performed element-wise:
   ```
   [[-9, -18, -27],
    [-6, -15, -24]]
   ```

4. Incompatible shapes - Here’s why this fails:

    1. Initial shapes:
       - **Shape of `z`**: `(3,)`
       - **Shape of `w`**: `(3, 2)`

    2. Padding with ones:
       - NumPy treats `z` as if it has shape `(1, 3)`.

    3. Attempt to stretch:
       - NumPy tries to stretch the shape `(1, 3)` to match `(3, 2)`.

    4. Checking compatibility:
       - For `z`'s shape `(1, 3)`:
         - The first dimension (1) can be stretched to 3 (okay).
         - The second dimension (3) cannot be stretched to 2 (incompatible).

    Because the dimensions cannot be aligned to make the shapes compatible (since 3 ≠ 2 and neither dimension is 1 that can be stretched), NumPy raises a `ValueError`. Here, the dimensions are incompatible for broadcasting because they cannot be made to align under the broadcasting rules, resulting in an error.

### Reshaping arrays

Reshaping refers to changing the dimensions of an array while keeping its data unchanged. We might want to reshape an array to suit the requirements of a particular operation or algorithm, like feeding data into a machine learning model that expects inputs in a specific shape. Reshaping means changing the way the data is organized within an array. When we reshape an array, we simply reorganize its elements to fit a new shape, but the total number of elements and the order of elements remain unchanged.

For reshaping to be possible, the total number of elements in the array must remain constant. This means the product of the dimensions in the new shape must equal the product of the dimensions in the original shape.

In [21]:
# Reshaping a 1D array to a 2D array
array = np.arange(12) # Creates an array with 12 elements
print("Original array:", array)
reshaped_array = array.reshape(3, 4) # Reshapes to a 3x4 array
print("Reshaped array:\n", reshaped_array)

# Reshape with one dimension calculated automatically
reshaped_array_auto = array.reshape(3, -1)
print("Reshaped array with -1:\n", reshaped_array_auto)

# Reshape back to a 1D array
one_d_array = reshaped_array.reshape(-1)
print("Reshaped back to 1D:\n", one_d_array)

# Creating a 3D array from a 1D array
three_d_array = array.reshape(2, 2, 3)
print("3D Reshaped Array:\n", three_d_array)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array with -1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped back to 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
3D Reshaped Array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


**Using `reshape` method**
- **Syntax**: `reshaped_array = original_array.reshape(new_shape)`
- `new_shape` is a tuple representing the desired shape. It can have as many dimensions as we need, provided that the total number of elements matches.
- Using `-1` as one of the dimensions in the tuple `new_shape` tells NumPy to automatically calculate that dimension to make the total number of elements match.
- `reshape(-1)` flattens the array back to a one-dimensional array.

#### Transpose
The transpose of an array is obtained by swapping its rows and columns. This operation is often used in linear algebra.

In [22]:
# 2D array transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix:\n", matrix)
transposed_matrix = matrix.T
print("Transposed matrix:\n", transposed_matrix)

# Higher-dimensional array transpose
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nOriginal 3D array:\n", array_3d)
transposed_3d = array_3d.transpose(1, 0, 2)
print("Transposed 3D array:\n", transposed_3d)

Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]

Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Transposed 3D array:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


For a 2D array (matrix), transposing switches its rows and columns. If you have a matrix where the element at position `(i, j)` is `matrix[i][j]`, after transposing, this element will be at position `(j, i)` in the transposed matrix.
- **Syntax**: `transposed_array = array.T`
- Each row of the original matrix becomes a column in the transposed matrix, and vice versa.

For higher-dimensional arrays, transposing can involve swapping any of the axes. NumPy provides the `transpose()` method, which allows us to specify the order of the axes.
- **Syntax**: `transposed_array = array.transpose(axes_order)`
- The function `array.transpose(axes_order)` rearranges the array dimensions according to the specified axes order. Each index represents the position of the original axes.
- For example, if we have an array of shape `(a, b, c)`, using `transpose(1, 0, 2)` will change it to `(b, a, c)`.

### Dot product
The dot product is used to compute the product of two arrays. It is often used in vector and matrix multiplication.

In [23]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

dot_product = np.dot(vector1, vector2)
print("Dot product of vectors:", dot_product)

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

dot_product_matrices = np.dot(matrix1, matrix2)
print("Dot product of matrices:\n", dot_product_matrices)

Dot product of vectors: 32
Dot product of matrices:
 [[19 22]
 [43 50]]


### Sorting arrays

In [24]:
### Sorting a 1D array
array = np.array([5, 2, 8, 1, 4])
print("Sorted array:", np.sort(array))
# Get indices that would sort the array
print("Indices that would sort the array:", np.argsort(array))
# In-place sorting
array.sort()
print("In-place sorted array:", array)

### Sorting a 2D array
array_2d = np.array([[3, 5, 1], [6, 2, 4]])
print("\nColumn-wise sorted 2D array:\n", np.sort(array_2d, axis=0)) # Sort each column
print("Row-wise sorted 2D array:\n", np.sort(array_2d, axis=1)) # Sort each row

Sorted array: [1 2 4 5 8]
Indices that would sort the array: [3 1 4 0 2]
In-place sorted array: [1 2 4 5 8]

Column-wise sorted 2D array:
 [[3 2 1]
 [6 5 4]]
Row-wise sorted 2D array:
 [[1 3 5]
 [2 4 6]]


### Comparison operators and filtering

In [25]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Element-wise comparison
print("a < b:", a < b)
print("a == b:", a == b)
print("a > b:", a > b)

# Using comparison to filter arrays
filtered_array = a[a > 3]
print("Filtered array (a > 3):", filtered_array)

# Using np.where for conditional logic
condition = np.where(a < b, a, b)
print("Element-wise minimum:", condition)

# Find unique elements
unique_elements = np.unique(a+b)
print("Unique elements:", unique_elements)

a < b: [ True  True False False False]
a == b: [False False  True False False]
a > b: [False False False  True  True]
Filtered array (a > 3): [4 5]
Element-wise minimum: [1 2 3 2 1]
Unique elements: [6]


- Filtering arrays using comparison - We can use comparison operators to filter arrays, selecting only elements that meet a certain condition.
    - **Syntax**: `filtered_array = array[condition]`
    
- Identifying unique elements with `np.unique` function.
    - **Syntax**: `unique_elements = np.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)`
        - `return_index`: If `True`, returns the indices of the first occurrences of the unique values in the original array.
        - `return_inverse`: If `True`, returns the indices to reconstruct the original array from the unique array.
        - `return_counts`: If `True`, returns the number of times each unique item appears in the array.
        - `axis`: The axis to apply the uniqueness check. If `None`, the array is flattened.

- Conditional logic with `np.where` - NumPy's `np.where` function is used to apply conditional logic across arrays. It selects elements from two arrays based on a specified condition.
    - **Syntax**: `result = np.where(condition, x, y)`
    - If `True`, it selects the element from `x`; otherwise, it selects from `y`.
    
### Logic functions

##### 1. Logical AND, OR, NOT
These functions perform element-wise logical operations.

In [26]:
# Define two arrays
array1 = np.array([True, False, True])
array2 = np.array([False, False, True])

print("Logical AND:", np.logical_and(array1, array2))
print("Logical OR:", np.logical_or(array1, array2))
print("Logical NOT:", np.logical_not(array1))

Logical AND: [False False  True]
Logical OR: [ True False  True]
Logical NOT: [False  True False]


- **`np.logical_and`**: Returns `True` only if both elements are `True`.
- **`np.logical_or`**: Returns `True` if at least one element is `True`.
- **`np.logical_not`**: Inverts the boolean value of each element.

##### 2. Comparison functions
These functions compare elements of arrays and return boolean arrays.

In [27]:
# Arrays for comparison
array1 = np.array([1, 2, 3])
array2 = np.array([3, 2, 1])

print("Equal:", np.equal(array1, array2))
print("Not equal:", np.not_equal(array1, array2))
print("Greater:", np.greater(array1, array2))
print("Less:", np.less(array1, array2))

Equal: [False  True False]
Not equal: [ True False  True]
Greater: [False False  True]
Less: [ True False False]


##### 3. Array comparison functions
These functions compare arrays and check if they are equal within some tolerance or exactly.

In [28]:
# Define arrays
array1 = np.array([1.0, 2.0, 3.0001])
array2 = np.array([1.0, 2.0, 3.0002])

# Check if arrays are close
close_result = np.allclose(array1, array2, rtol=1e-03)
print("All close:", close_result)

# Check element-wise closeness
isclose_result = np.isclose(array1, array2, rtol=1e-03)
print("Element-wise close:", isclose_result)

# Check if arrays are exactly equal
equal_result = np.array_equal(array1, array2)
print("Array equal:", equal_result)

All close: True
Element-wise close: [ True  True  True]
Array equal: False


- `np.allclose`: Returns `True` if all elements are approximately equal, considering specified tolerances. Useful for floating-point comparisons.
- `np.isclose`: Returns an array of booleans where each element indicates if the corresponding elements in the input arrays are close.
- `np.array_equal`: Returns `True` if arrays are exactly equal in shape and element values.

##### 4. Truth value testing
These functions test whether any or all elements in an array meet a condition.

In [29]:
array = np.array([True, True, False])
 
print("All elements True:", np.all(array))
print("Any element True:", np.any(array))

All elements True: False
Any element True: True
