# Introduction to TensorFlow

TensorFlow is a library for numerical computation and deep learning. It is widely used for building deep learning models and it allows developers to create large-scale neural networks with many layers

### Why use TensorFlow?

- Flexibility: TensorFlow supports both high-level and low-level APIs, allowing to create models using predefined functions or customize them as needed. TensorFlow provides a high-level API (Keras) that makes building and training neural networks simple.
- Performance: It can run on various platforms, including CPUs, GPUs, and TPUs, which allows for high performance in different environments.

In [1]:
# Importing TensorFlow
import tensorflow as tf
import numpy as np

It is common to import tensorflow with the alias `tf`

### Creating tensors
Tensors are the core data structures in TensorFlow. They are similar to NumPy arrays but have additional capabilities for GPU acceleration.

#### Constant tensor
Tensors created with `tf.constant()` are immutable, meaning their values cannot be changed once defined. They are ideal for fixed data that will not be modified during a program's execution.

In [2]:
# Creating a constant tensor
tensor = tf.constant([[1, 2], [3, 4]])
print("Tensor:", tensor)

Tensor: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


**Syntax**: `tf.constant(value, dtype=None, shape=None, name='Const')`
  - `value`: The initial value of the tensor. This can be a Python list or a NumPy array.
  - `dtype`: (Optional) The data type of the elements in the tensor. If not specified, it is inferred from the `value`.
  - `shape`: (Optional) The desired shape of the tensor. If not specified, it is inferred from the `value`.
  - `name`: (Optional) The name of the operation.
  
#### Variables
Variables are used to store mutable state in TensorFlow. Tensors created with `tf.Variable()` are mutable, allowing their values to be updated. This makes them suitable for parameters that need to be adjusted during training, such as weights and biases in neural networks.

In [3]:
# Creating a variable tensor
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
print(variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


**Syntax**: `tf.Variable(initial_value, trainable=True, name=None, dtype=None)`
  - `initial_value`: The initial value of the variable. It can be a constant or a tensor.
  - `trainable`: (Optional) If `True`, the variable will be included in the gradient computations.
  - `dtype`: (Optional) The data type of the elements in the variable.
  
Although variable behaves like a tensor in many respects, it has additional capabilities such as being updatable and trackable. The primary difference is that a variable can change its state (value) over time, while a tensor represents a fixed state.

#### Random tensors
Random tensors are often used for initializing weights in neural networks or generating synthetic data. TensorFlow provides several functions to create random tensors.

In [4]:
# Creating a random tensor with a normal distribution
random_tensor = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)
print(random_tensor)

# Creating a random tensor with a uniform distribution
uniform_tensor = tf.random.uniform(shape=(2, 2), minval=0, maxval=1)
print(uniform_tensor)

tf.Tensor(
[[0.8434814 0.9683882]
 [0.5223029 3.1693513]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.57607687 0.9728943 ]
 [0.09842479 0.9611082 ]], shape=(2, 2), dtype=float32)


**Syntax** for `tf.random.normal()`: `tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)`
  - `shape`: The shape of the output tensor.
  - `mean`: The mean of the normal distribution.
  - `stddev`: The standard deviation of the normal distribution.
  - `seed`: (Optional) A random seed for generating reproducible results.

**Syntax** for `tf.random.uniform()`: `tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)`
  - `minval`: The lower bound of the uniform distribution.
  - `maxval`: The upper bound of the uniform distribution.

#### Using built-in functions

TensorFlow provides several built-in functions for creating tensors with specific values, which are useful for initializing layers and models.

In [5]:
# Creating a tensor filled with ones
ones_tensor = tf.ones(shape=(3, 3))
print("Tensor filled with ones:\n", ones_tensor)

# Creating a tensor filled with zeros
zeros_tensor = tf.zeros(shape=(3, 3))
print("Tensor filled with zeros:\n", zeros_tensor)

# Creating a tensor filled with a specified value
filled_tensor = tf.fill([2, 2], value=9)
print("Tensor filled with value 9:\n", filled_tensor)

# Creating an identity matrix
identity_tensor = tf.eye(3)
print("Identity matrix:\n", identity_tensor)

Tensor filled with ones:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
Tensor filled with zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
Tensor filled with value 9:
 tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)
Identity matrix:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


### Setting the seed
Setting a seed ensures that random operations produce the same results each time they are run. This is crucial for reproducibility in experiments.

In [6]:
# Setting the global random seed
tf.random.set_seed(42)

# Creating a random tensor with a set seed
random_tensor_seeded = tf.random.normal(shape=(2, 2))
print(random_tensor_seeded)

tf.Tensor(
[[ 0.3274685 -0.8426258]
 [ 0.3194337 -1.4075519]], shape=(2, 2), dtype=float32)


**Syntax**: `tf.random.set_seed(seed)`
  - `seed`: An integer value used to initialize the random number generator. This value determines the sequence of random numbers generated.

### Shuffling a tensor

Shuffling is important in machine learning to prevent the model from learning patterns in the order of the data. 

In [7]:
# Creating a tensor
data_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])

# Shuffling the tensor
shuffled_tensor = tf.random.shuffle(data_tensor)
print(shuffled_tensor)

tf.Tensor(
[[5 6]
 [1 2]
 [7 8]
 [3 4]], shape=(4, 2), dtype=int32)


**Syntax**: `tf.random.shuffle(value, seed=None, name=None)`
  - `value`: The input tensor to shuffle.
  - `seed`: (Optional) An integer seed for the shuffle operation to produce reproducible results.
  - `name`: (Optional) A name for the operation.

We can set an operation-level seed to ensure specific operations produce the same result independently of global seeds. To achieve reproducibility, it's often necessary to set both a global seed and an operation-specific seed. This approach ensures that your random operations yield the same results across different runs.

- Global seed: By setting a global seed using `tf.random.set_seed(42)`, we make sure that TensorFlow's random number generation is consistent across different runs.
- Operation seed: An additional seed on specific operations (`seed=24` in `tf.random.shuffle`) ensures that particular operations behave consistently each time they are executed within the same global context.

In [8]:
# Setting the global random seed
tf.random.set_seed(42)

# Setting a random seed for the shuffle operation
shuffled_tensor_seeded = tf.random.shuffle(data_tensor, seed=24)
print(shuffled_tensor_seeded)

tf.Tensor(
[[3 4]
 [1 2]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


### Tensor attributes
Tensors have several important attributes that provide information about their properties. Understanding these attributes is crucial for working effectively with TensorFlow.

In [9]:
example_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Shape
print("Shape of the tensor:", example_tensor.shape)

# Data type
print("Data type of the tensor:", example_tensor.dtype)

# Rank (number of dimensions)
print("Rank of the tensor:", tf.rank(example_tensor))
# Rank using ndim
print("Rank of the tensor using ndim:", example_tensor.ndim)

# Size (total number of elements)
print("Size of the tensor:", tf.size(example_tensor).numpy())

Shape of the tensor: (2, 3)
Data type of the tensor: <dtype: 'int32'>
Rank of the tensor: tf.Tensor(2, shape=(), dtype=int32)
Rank of the tensor using ndim: 2
Size of the tensor: 6


- **Shape**: The shape of a tensor is a tuple of integers that describes the number of elements in each dimension. It can be accessed using the `shape` attribute. For example, the shape of a 2x3 matrix is `(2, 3)`.
- **Data type**: The data type (`dtype`) of a tensor indicates the type of elements contained in the tensor, such as `tf.int32`, `tf.float32`, etc. It is important to ensure that operations are performed on compatible data types.
- **Rank**: The rank of a tensor refers to the number of dimensions it has. For instance, a scalar has a rank of 0, a vector has a rank of 1, and a matrix has a rank of 2.
- **Size**: The size of a tensor represents the total number of elements in the tensor. It can be determined using `tf.size()` and is useful for understanding the overall data volume.

### Converting data types in tensors
In TensorFlow, tensors can have different data types such as `float32`, `int32`, `int64`, etc. Converting tensors between these data types can be necessary for various reasons, such as ensuring compatibility with specific operations, reducing memory usage, or meeting the requirements of a model or algorithm.

#### Casting
The primary method to change the data type of a tensor is using the `tf.cast` function. This function casts a tensor to a specified data type.

In [10]:
# Original tensor with float32 data type
tensor_float = tf.constant([1.5, 2.5, 3.5], dtype=tf.float32)
print("Original tensor (float32):\n", tensor_float)

# Casting tensor to int32
tensor_int = tf.cast(tensor_float, dtype=tf.int32)
print("Cast tensor (int32):\n", tensor_int)

Original tensor (float32):
 tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
Cast tensor (int32):
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


**Syntax**: `tf.cast(tensor, dtype)`
  - `tensor`: The tensor whose data type you want to change.
  - `dtype`: The desired data type.
  
When converting from a higher precision data type (e.g., `float64`) to a lower precision data type (e.g., `float32` or `int32`), there may be a loss of precision.

#### Converting to floating-point types
Converting integers to floating-point types can be necessary for computations that require decimal precision, such as in neural network training.

In [11]:
# Original tensor with int32 data type
tensor_int = tf.constant([1, 2, 3], dtype=tf.int32)
print("Original tensor (int32):\n", tensor_int)

# Casting tensor to float32
tensor_float = tf.cast(tensor_int, dtype=tf.float32)
print("Cast tensor (float32):\n", tensor_float)

Original tensor (int32):
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Cast tensor (float32):
 tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


#### Converting to boolean type
Boolean type conversion is useful for conditions or mask operations.

In [12]:
# Original tensor with float32 data type
tensor_float = tf.constant([0.0, 1.0, 2.0], dtype=tf.float32)
print("Original tensor (float32):\n", tensor_float)

# Casting tensor to boolean
tensor_bool = tf.cast(tensor_float, dtype=tf.bool)
print("Cast tensor (bool):\n", tensor_bool)

Original tensor (float32):
 tf.Tensor([0. 1. 2.], shape=(3,), dtype=float32)
Cast tensor (bool):
 tf.Tensor([False  True  True], shape=(3,), dtype=bool)


### Tensor operations
We can perform various mathematical operations with tensors. TensorFlow operations are functions that take tensors as input and produce tensors as output.

#### Element-wise operations
Element-wise operations are performed on corresponding elements of tensors.

In [13]:
# Arithmetic operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, -6], [7, 8]])

print("Addition:\n", tf.add(a, b))
print("Subtraction:\n", tf.subtract(a, b))
print("Multiplication:\n", tf.multiply(a, b))
print("Division:\n", tf.divide(a, b))
print("Exponentiation:\n", tf.math.pow(a, 2))
print("Absolute value:\n", tf.math.abs(b))
print("Cumulative sum:\n", tf.math.cumsum(a, axis=0))
print("Cumulative product:\n", tf.math.cumprod(a, axis=0))

print("Square root:\n", tf.math.sqrt(tf.cast(a, dtype=tf.float32)))
print("Logarithm:\n", tf.math.log(tf.cast(a, dtype=tf.float32)))
print("Exponential:\n", tf.math.exp(tf.cast(a, dtype=tf.float32)))
print("Reciprocal (1/x):\n", tf.math.reciprocal(tf.cast(a, dtype=tf.float32)))

Addition:
 tf.Tensor(
[[ 6 -4]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction:
 tf.Tensor(
[[-4  8]
 [-4 -4]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[  5 -12]
 [ 21  32]], shape=(2, 2), dtype=int32)
Division:
 tf.Tensor(
[[ 0.2        -0.33333333]
 [ 0.42857143  0.5       ]], shape=(2, 2), dtype=float64)
Exponentiation:
 tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
Absolute value:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
Cumulative sum:
 tf.Tensor(
[[1 2]
 [4 6]], shape=(2, 2), dtype=int32)
Cumulative product:
 tf.Tensor(
[[1 2]
 [3 8]], shape=(2, 2), dtype=int32)
Square root:
 tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)
Logarithm:
 tf.Tensor(
[[0.        0.6931472]
 [1.0986123 1.3862944]], shape=(2, 2), dtype=float32)
Exponential:
 tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)
Reciprocal (1/x):
 tf.Tensor(
[[1.         0.5       ]
 [0.33333334 0.25 

#### Matrix operations

In [14]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Matrix multiplication using 'matmul':\n", tf.matmul(a, b))
print("Matrix multiplication using 'tensordot':\n", tf.tensordot(a, b, axes=1))
print("Transpose:\n", tf.transpose(a))
print("Inverse matrix:\n", tf.linalg.inv(tf.cast(a, dtype=tf.float32)))
print("Determinant:\n", tf.linalg.det(tf.cast(a, dtype=tf.float32)))
print("Trace:\n", tf.linalg.trace(a))

Matrix multiplication using 'matmul':
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Matrix multiplication using 'tensordot':
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Transpose:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
Inverse matrix:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
Determinant:
 tf.Tensor(-2.0, shape=(), dtype=float32)
Trace:
 tf.Tensor(5, shape=(), dtype=int32)


### Indexing and slicing tensors

* Indexing allows us to access specific elements or sub-tensors within a larger tensor. TensorFlow supports various indexing techniques similar to those used in NumPy.
* Slicing allows us to extract a sub-tensor from a larger tensor based on specified ranges of indices.

In [15]:
# Creating a tensor
tensor = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])

# Indexing
print("Element:\n", tensor[0, 1]) # Accessing a specific element - element at row 0, column 1
print("Row:\n", tensor[1]) # Accessing a row - entire row 1
print("Column:\n", tensor[:, 2]) # Accessing a column - entire column 2
print("Selected elements:\n", tf.gather(tensor, [1, 0], axis=1)) # Indexing with a list

# Slicing
print("Sliced tensor:\n", tensor[0, 1:3]) # Slicing a sub-tensor - elements from index 1 to 2 in row 0
print("Sliced tensor with step:\n", tensor[:, 0:4:2]) # Slicing with step size - every second element in each row
print("Sliced tensor with tf.slice:\n", tf.slice(tensor, begin=[0, 1], size=[1, 2])) # Slicing with tf.slice - starting from (0, 1) with size (1, 2)

# Multi-dimensional slicing
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Multi-Dimensional Sliced Tensor:\n", tensor[0:2, 0:1, :]) # Slicing in 3D tensor

Element:
 tf.Tensor(2, shape=(), dtype=int32)
Row:
 tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
Column:
 tf.Tensor([3 7], shape=(2,), dtype=int32)
Selected elements:
 tf.Tensor(
[[2 1]
 [6 5]], shape=(2, 2), dtype=int32)
Sliced tensor:
 tf.Tensor([2 3], shape=(2,), dtype=int32)
Sliced tensor with step:
 tf.Tensor(
[[1 3]
 [5 7]], shape=(2, 2), dtype=int32)
Sliced tensor with tf.slice:
 tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
Multi-Dimensional Sliced Tensor:
 tf.Tensor(
[[[1 2 3]]

 [[7 8 9]]], shape=(2, 1, 3), dtype=int32)


##### Indexing
- Access individual elements or slices of a tensor using Python indexing.
    - **Syntax**: `tensor[index]`
      - `index`: The position of the element or slice to access.

- `tf.gather()` allows for advanced indexing by gathering slices from the tensor along a specified axis.
    - **Syntax**: `tf.gather(params, indices, axis)`
      - `params`: The tensor to gather slices from.
      - `indices`: The indices of the slices to gather.
      - `axis`: The axis along which to gather slices.
      
##### Slicing
- Extract sub-tensors by specifying ranges for each dimension.
    - **Syntax**: `tensor[start:stop:step]`
      - `start`: The starting index.
      - `stop`: The ending index.
      - `step`: (Optional) The step size between indices.

- The `tf.slice()` function provides more explicit control over slicing by specifying offsets and sizes for each dimension.
    - **Syntax**: `tf.slice(input_, begin, size)`
      - `input_`: The tensor to slice.
      - `begin`: A list or tensor specifying the starting indices.
      - `size`: A list or tensor specifying the size of the slice.
      
### Broadcasting
Broadcasting is a feature in TensorFlow (and in other numerical computing libraries like NumPy) that allows for element-wise operations on tensors of different shapes. Broadcasting enables us to perform arithmetic operations on tensors without requiring explicit reshaping or replication of data, simplifying code and improving performance.

When tensors with different shapes are involved in an operation, TensorFlow automatically adjusts their shapes to make them compatible. This adjustment is done according to specific rules, which involve expanding dimensions and replicating data where necessary.

The broadcasting rules are:
1. If the tensors have different ranks (number of dimensions), the shape of the tensor with fewer dimensions is padded with ones on the left side until both shapes have the same length.
2. Tensors are compatible when:
   - The sizes of the dimensions are equal, or
   - One of the sizes is 1.
3. If the dimensions of the tensors are not compatible according to these rules, broadcasting is not possible, and an error will be raised.

In [16]:
### Example 1: Scalar and tensor
tensor = tf.constant([[1, 2], [3, 4]])
scalar = tf.constant(5)

# Broadcasting scalar to add to each element of the tensor
result = tensor + scalar
print("Broadcasting scalar:\n", result)


### Example 2: Vector and matrix
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
vector = tf.constant([10, 20, 30])

# Broadcasting vector to add to each row of the matrix
result = matrix + vector
print("\nBroadcasting vector:\n", result)


### Example 3: Different shapes
tensor1 = tf.constant([[1], [2], [3]])   # Shape (3, 1)
tensor2 = tf.constant([10, 20, 30])      # Shape (3,)

# Broadcasting tensor2 to add to each column of tensor1
result = tensor1 + tensor2
print("\nBroadcasting different shapes:\n", result)


### Example 4: Broadcasting with explicit reshaping
tensor1 = tf.constant([[1, 2], [3, 4]])          # Shape (2, 2)
tensor2 = tf.constant([10, 20])                  # Shape (2,)
# Reshaping tensor2 to match tensor1 for broadcasting
tensor2_reshaped = tf.reshape(tensor2, shape=(2, 1))

# Broadcasting reshaped tensor2 to add to tensor1
result = tensor1 + tensor2_reshaped
print("\nBroadcasting with explicit reshaping:\n", result)

Broadcasting scalar:
 tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)

Broadcasting vector:
 tf.Tensor(
[[11 22 33]
 [14 25 36]], shape=(2, 3), dtype=int32)

Broadcasting different shapes:
 tf.Tensor(
[[11 21 31]
 [12 22 32]
 [13 23 33]], shape=(3, 3), dtype=int32)

Broadcasting with explicit reshaping:
 tf.Tensor(
[[11 12]
 [23 24]], shape=(2, 2), dtype=int32)


##### Explanations

1. Example 1: scalar and tensor
   - Rule applied: Scalars are automatically broadcast to any shape. This is because a scalar can be thought of as a tensor with shape `()`, and it can expand to match any tensor’s shape.
   - Explanation: The scalar `5` is broadcast to match the shape of the tensor `[[1, 2], [3, 4]]`, which has a shape of `(2, 2)`. The scalar is conceptually expanded to a 2x2 tensor `[[5, 5], [5, 5]]` and then added element-wise, resulting in `[[6, 7], [8, 9]]`.

2. Example 2: Vector and matrix

   - Rule applied: When the dimensions are different, the smaller tensor (vector) is padded with ones on the left, turning `(3,)` into `(1, 3)`. The vector can then be broadcast across the matrix rows.
   - Explanation: The vector `[10, 20, 30]` with shape `(3,)` is effectively reshaped to `(1, 3)` to match the shape of the matrix `(2, 3)`. It is then broadcast to match the matrix dimensions by replicating the vector along the new axis. This results in each row of the matrix having `[10, 20, 30]` added to it, yielding `[[11, 22, 33], [14, 25, 36]]`.

3. Example 3: Different shapes

   - Rule applied: One of the dimensions is 1. This allows `tensor2` to be broadcast along the second dimension of `tensor1`.
   - Explanation: `tensor1` has shape `(3, 1)`, and `tensor2` has shape `(3,)`. The shape `(3,)` is interpreted as `(1, 3)`. The first dimension of `tensor1` matches, and the second dimension is broadcast by expanding `tensor2` across each row. This results in adding `tensor2` to each row of `tensor1`, resulting in a shape of `(3, 3)`, where the output is `[[11, 12, 13], [22, 23, 24], [33, 34, 35]]`.

4. Example 4: Broadcasting with explicit reshaping

   - Rule applied: Reshaping helps manually adjust dimensions to fit broadcasting rules.
   - Explanation: `tensor1` has shape `(2, 2)`, and `tensor2` has shape `(2,)`, which we reshape to `(2, 1)` to align with the first dimension of `tensor1`. Now `tensor2_reshaped` can be broadcast to `(2, 2)`. Each element of `tensor2_reshaped` is broadcasted across the columns of `tensor1`. The operation adds the reshaped `tensor2` to each column, resulting in `[[11, 12], [23, 24]]`.
   
### Reshaping tensors
Reshaping tensors allows us to change the shape of a tensor without altering its data. Reshaping is often necessary when preparing data for model input or when manipulating data to perform specific operations. A tensor's shape describes the size of each dimension. Reshaping involves changing the dimensions while keeping the total number of elements constant. This means the product of the dimensions before and after reshaping must be the same. The primary function for reshaping tensors in TensorFlow is `tf.reshape()`.

In [17]:
#### Example 1: Flattening a tensor
# Creating a 2D tensor
tensor_2d = tf.constant([[1, 2], [3, 4], [5, 6]])

# Reshaping to a 1D tensor (flattening)
flattened_tensor = tf.reshape(tensor_2d, [-1])
print("Flattened tensor:\n", flattened_tensor)


#### Example 2: Changing dimensions
# Creating a 1D tensor
tensor_1d = tf.constant([1, 2, 3, 4, 5, 6])

# Reshaping to a 2D tensor
reshaped_tensor = tf.reshape(tensor_1d, [2, 3])
print("Reshaped tensor to 2D:\n", reshaped_tensor)


#### Example 3: Adding a dimension
# Creating a 2D tensor
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])

# Adding a new dimension to create a 3D tensor
reshaped_tensor = tf.reshape(tensor_2d, [2, 3, 1])
print("3D Tensor with added dimension:\n", reshaped_tensor)


#### Example 4: Using `-1` for automatic inference
# Creating a 3D tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Reshaping using -1 for automatic inference
reshaped_tensor = tf.reshape(tensor_3d, [2, -1])
print("Reshaped tensor with inferred dimension:\n", reshaped_tensor)

Flattened tensor:
 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
Reshaped tensor to 2D:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
3D Tensor with added dimension:
 tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]], shape=(2, 3, 1), dtype=int32)
Reshaped tensor with inferred dimension:
 tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


- **Syntax**: `tf.reshape(tensor, shape)`
  - `tensor`: The tensor to reshape.
  - `shape`: A list or tuple specifying the new shape.
  
##### Explanations
1. Example 1: Flattening a tensor involves converting a multi-dimensional tensor into a 1D tensor. This is useful when we need to feed data into a neural network layer that requires a vector input. The shape `[-1]` automatically infers the size needed to flatten the tensor into a 1D array, resulting in `[1, 2, 3, 4, 5, 6]`.
2. Example 2: We can change the dimensions of a tensor, provided the total number of elements remains the same. The original tensor with shape `(6,)` is reshaped to `(2, 3)`, resulting in a 2D tensor `[[1, 2, 3], [4, 5, 6]]`.
3. Example 3: Adding a new dimension can be useful for adjusting the shape to fit model input requirements. The tensor is reshaped from `(2, 3)` to `(2, 3, 1)`, adding a new dimension without changing the total number of elements.
4. Example 4: The `-1` in the shape allows TensorFlow to infer the appropriate size for that dimension. The original tensor with shape `(2, 2, 2)` is reshaped to `(2, 4)`, where `-1` infers the second dimension.

### Squeezing a tensor
Squeezing a tensor involves removing dimensions of size 1 from its shape. This operation is useful when we need to simplify the tensor's shape, often to make it compatible with certain operations or layers. The `tf.squeeze()` function removes all dimensions with size 1 from a tensor's shape.

In [18]:
#### Example 1: Squeezing all single dimensions
# Creating a tensor with single dimensions
tensor = tf.constant([[[1], [2], [3]]])  # Shape (1, 3, 1)

# Squeezing all dimensions of size 1
squeezed_tensor = tf.squeeze(tensor)
print("Squeezed tensor:\n", squeezed_tensor)


#### Example 2: Squeezing specific dimensions
# Creating a tensor with single dimensions
tensor = tf.constant([[[1], [2], [3]]])  # Shape (1, 3, 1)

# Squeezing a specific dimension (e.g., axis 0)
squeezed_tensor_axis = tf.squeeze(tensor, axis=0)
print("Tensor squeezed at axis 0:\n", squeezed_tensor_axis)

Squeezed tensor:
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor squeezed at axis 0:
 tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


- **Syntax**: `tf.squeeze(tensor, axis=None)`
  - `tensor`: The tensor to squeeze.
  - `axis`: (Optional) An integer or list of integers specifying which specific dimensions to squeeze. If not specified, all dimensions with size 1 will be removed.

##### Explanations
1. Example 1: The tensor with shape `(1, 3, 1)` is squeezed to `(3,)`, removing both dimensions with size 1.
2. Example 2: By specifying `axis=0`, only the dimension at position 0 is removed, resulting in a shape of `(3, 1)`.

### One-hot encoding
One-hot encoding is a technique used to convert categorical data into a format suitable for machine learning models. It transforms each category into a vector where only one element is "hot" (set to 1), and all others are "cold" (set to 0). The `tf.one_hot()` function creates a one-hot representation of a tensor.

In [19]:
#### Example 1: Basic one-hot encoding
# Indices representing categories
indices = tf.constant([0, 1, 2, 1])

# One-hot encode with depth of 3
one_hot_encoded = tf.one_hot(indices, depth=3)
print("One-hot encoded tensor:\n", one_hot_encoded)


#### Example 2: Custom axis for one-hot encoding
# Indices representing categories
indices = tf.constant([0, 1, 2, 1])

# One-hot encode with depth of 3, placing vectors along a new first axis
one_hot_encoded_axis = tf.one_hot(indices, depth=3, axis=0)
print("One-hot encoded tensor with custom axis:\n", one_hot_encoded_axis)

One-hot encoded tensor:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]], shape=(4, 3), dtype=float32)
One-hot encoded tensor with custom axis:
 tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)


- **Syntax**: `tf.one_hot(indices, depth, axis=None, dtype=tf.float32)`
  - `indices`: A tensor of indices to be converted into one-hot vectors.
  - `depth`: The number of categories (i.e., the length of the one-hot vectors).
  - `axis`: (Optional) The axis to place the one-hot vectors. Defaults to the last axis.
  - `dtype`: The data type of the output tensor (default is `tf.float32`).

##### Explanations
1. Example 1: The `depth` is set to `3`, meaning there are three possible categories (0, 1 and 2). This specifies the length of each one-hot vector. The `indices` tensor `[0, 1, 2, 1]` is one-hot encoded with a `depth` of 3, resulting in a tensor where each index is represented as a one-hot vector. The resulting tensor has a shape of `(4, 3)` because there are four indices and each one is converted to a vector of length `3`.
2. Example 2: By setting `axis=0`, the one-hot vectors are arranged along the first axis, resulting in a different tensor structure.

### Manipulating variable tensors
`tf.Variable` allows us to change the value of the tensor, making it ideal for representing model parameters like weights and biases that need to be updated during training. We can update the value of a `tf.Variable` using TensorFlow operations such as `assign()`, `assign_add()`, and `assign_sub()`. These operations change the state of the variable in place.

In [20]:
# Creating a variable with an initial value
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
print("Initial variable:\n", variable)

# Assign a new value to the variable
variable.assign([[5.0, 6.0], [7.0, 8.0]])
print("Updated variable with assign:\n", variable)

# Add to the variable
variable.assign_add([[1.0, 1.0], [1.0, 1.0]])
print("Updated variable with assign_add:\n", variable)

# Subtract from the variable
variable.assign_sub([[2.0, 2.0], [2.0, 2.0]])
print("Updated variable with assign_sub:\n", variable)

Initial variable:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
Updated variable with assign:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>
Updated variable with assign_add:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[6., 7.],
       [8., 9.]], dtype=float32)>
Updated variable with assign_sub:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[4., 5.],
       [6., 7.]], dtype=float32)>


Methods for updating variables:
1. **assign()**: Assigns a new value to the variable.
   - **Syntax**: `variable.assign(new_value)`

2. **assign_add()**: Adds a value to the current variable.
   - **Syntax**: `variable.assign_add(value)`

3. **assign_sub()**: Subtracts a value from the current variable.
   - **Syntax**: `variable.assign_sub(value)`
   
The new value assigned to a variable must have the same shape and data type as the variable.
   
#### Converting variables to tensors
A `tf.Variable` can be easily converted to a tensor using the `tf.convert_to_tensor()` function. This is useful for performing tensor operations on variables. When we convert a variable to a tensor, we are creating a tensor that reflects the current value of the variable. This conversion allows us to use the variable's current value in tensor operations that specifically require tensors, such as mathematical operations or when passing data to layers in a neural network.

In [21]:
# Convert variable to tensor
tensor_version = tf.convert_to_tensor(variable)
print("Tensor version:\n", tensor_version)

Tensor version:
 tf.Tensor(
[[4. 5.]
 [6. 7.]], shape=(2, 2), dtype=float32)


### TensorFlow interaction with NumPy
TensorFlow and NumPy are both libraries for numerical computation in Python, but they are optimized for different tasks. NumPy is excellent for general-purpose numerical computing, while TensorFlow is designed for deep learning and GPU acceleration. TensorFlow and NumPy can interact seamlessly, allowing us to leverage the strengths of both.

In [22]:
# Convert the NumPy array to a TensorFlow tensor
array = np.array([[1, 2], [3, 4]])
print("NumPy array:\n", array)
tensor = tf.convert_to_tensor(array)
print("TensorFlow tensor from NumPy array:\n", tensor)

# Convert a TensorFlow tensor to a NumPy array
array_from_tensor = tensor.numpy()
print("NumPy array from TensorFlow tensor:\n", array_from_tensor)


# Use a NumPy function on a TensorFlow tensor
np_result = np.add(tensor, 10)
print("Using NumPy function on TensorFlow tensor:\n", np_result)

# Use a TensorFlow function on a NumPy array
tf_result = tf.add(array, 10)
print("Using TensorFlow function on NumPy array:\n", tf_result)

NumPy array:
 [[1 2]
 [3 4]]
TensorFlow tensor from NumPy array:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
NumPy array from TensorFlow tensor:
 [[1 2]
 [3 4]]
Using NumPy function on TensorFlow tensor:
 [[11 12]
 [13 14]]
Using TensorFlow function on NumPy array:
 tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
